version: '3.7'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: